name: Deploy HTML

on:
  push:
    branches: ["main"] # O "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './' # Path del file/cartella da pubblicare
      - uses: actions/deploy-pages@v4
